GET http://localhost:3001/api/blogs
###
GET http://localhost:3001/api/blogs/1
###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "This is a post test",
    "author": "Leonardo N Ghiggino",
    "url": "http://localhost:3001/teste/teste",
    "likes": 0
}
###
DELETE http://localhost:3001/api/blogs/635a6b7de718bcff9d5fdb3a