

POST http://localhost:3003/api/blogs 
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxnaGlnZ2lubyIsImlkIjoiNjE1MTA4NmRmYjdmZDYxN2Q2MDhjNDgyIiwiaWF0IjoxNjMyNzAxNDQ0LCJleHAiOjE2MzI3MDUwNDR9.CYQA4EAz-lAR9KPiTeosAk1LZIIYOOgVGb39doS4nGs

{
    "title": "will the id be saved correctly?", 
    "author": "Leonardo Ghiggino", 
    "url": "www.willthisshitwork.com", 
    "likes": "2021",
    "user": "6151086dfb7fd617d608c482"
}


# cazuza = 614fa85e4e23ae24a4813b1e
#lghiggino = 6151086dfb7fd617d608c482